server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: movie-service-route
          uri: ${MOVIE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/movies/**
        - id: recommendation-service-route
          uri: ${RECOMMENDATION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/recommendations/**
